#!/usr/bin/env bash
# Takes a subdomain and a domain and returns information about the subdomain

function get_dns_record {
  local domain=$1
  local subdomain=$2
  dig $subdomain.$domain | awk '/^'$subdomain'\.'$domain'\./ {type=$4; dest=$5} END {print "The subdomain " $1 " is a " type " record and points to " dest}'
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
  # audit all subdomains
  get_dns_record $domain www
  get_dns_record $domain lb-01
  get_dns_record $domain web-01
  get_dns_record $domain web-02
else
  # audit specific subdomain
  get_dns_record $domain $subdomain
fi
