#!/usr/bin/env bash
# Takes a subdomain and a domain and returns information about the subdomain

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
  # audit all subdomains
  get_dns_record $domain www
  get_dns_record $domain lb-01
  get_dns_record $domain web-01
  get_dns_record $domain web-02
else
  # audit specific subdomain
  get_dns_record $domain $subdomain
fi
