#!/usr/bin/env bash
# The script restarts gunicorn app

# Find the Gunicorn master process ID
gunicorn_master_pid=$(ps aux | grep gunicorn | grep -v grep | awk '{if($3 == 0.0) print $2}')

# Check if the Gunicorn master process ID was found
if [ -z "$gunicorn_master_pid" ]; then
    echo "Gunicorn master process not found."
    exit 1
fi

# Send the HUP signal to the Gunicorn master process to gracefully reload
kill -HUP $gunicorn_master_pid

echo "Gunicorn has been gracefully reloaded."
