#!/usr/bin/env bash
# The script restarts gunicorn app

# Get the PID of the Gunicorn process
PID=$(pgrep gunicorn | head -n 1)
# Send a HUP signal to the process to gracefully reload the workers
kill -HUP "$PID"
